version: '3.8'

services:
  sam-mask-service:
    build: .
    container_name: sam-mask-service
    ports:
      - "8739:8739"
    volumes:
      # Mount models directory to persist downloaded models
      - type: bind
        source: ./models
        target: /app/models
        is_directory: true  # Coolify will create this directory
    environment:
      # API Key (optional - Coolify will show in UI)
      - SAM_API_KEY=${SAM_API_KEY:-}
      # CPU-only mode (no GPU required)
      - CUDA_VISIBLE_DEVICES=""
      # Python optimizations
      - PYTHONUNBUFFERED=1
      # Optimisations CPU pour PyTorch (match votre PC local)
      - OMP_NUM_THREADS=12  # Plus de threads pour 6 CPUs
      - TORCH_NUM_THREADS=12
      - MKL_NUM_THREADS=12
      - OPENBLAS_NUM_THREADS=12
      - VECLIB_MAXIMUM_THREADS=12
      - NUMEXPR_NUM_THREADS=12
      # Performance maximale
      - KMP_AFFINITY=granularity=fine,verbose,compact,1,0
      - KMP_BLOCKTIME=1
      - KMP_SETTINGS=1
      # Coolify magic variables (optional)
      - SERVICE_FQDN_SAM_8739=/api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8739/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for CPU deployment
    deploy:
      resources:
        limits:
          cpus: '6'  # Utiliser 6 CPUs sur 8
          memory: 16G  # 16GB RAM pour éviter swapping
        reservations:
          cpus: '4'  # Garantir 4 CPUs minimum
          memory: 8G  # Garantir 8GB RAM minimum
    # Coolify labels for proxy (optional - if you want public access)
    labels:
      - coolify.managed=true
      - traefik.enable=true
      - "traefik.http.routers.sam-mask.rule=Host(`${SERVICE_FQDN_SAM}`) && PathPrefix(`/`)"
      - traefik.http.routers.sam-mask.entryPoints=http